# Generated by Django 2.1 on 2018-08-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='instrument',
            field=models.CharField(choices=[('s', 'Singer'), ('g', 'Guitar'), ('b', 'Bass'), ('d', 'Drums')], max_length=1),
        ),
    ]
